---
atomposition:
  - - 0.0
    - 0.0
    - 0.0
  - - 0.5
    - 0.5
    - 0.5
lattice:
  - - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 1.0
    - 0.0
  - - 0.0
    - 0.0
    - 1.0
lmax: 4
name: superstructure